
# Файл конфигурации для Netlify

[build]
  # Команда для сборки вашего Next.js проекта
  command = "next build"
  # Директория, куда Next.js складывает статические файлы для публикации
  # Netlify Next.js runtime обычно обрабатывает это автоматически,
  # но указание может быть полезным.
  # publish = ".next" # Для стандартного Next.js
  # Для Next.js с output: 'standalone' или если Netlify использует свой runtime,
  # это может отличаться или управляться автоматически.
  # Оставляем publish как есть, Netlify должен справиться с Next.js по умолчанию.

[build.environment]
  # Здесь можно указать переменные окружения, специфичные для сборки,
  # но лучше их задавать через UI Netlify для безопасности.
  # NODE_VERSION = "18" # Пример, если нужна определенная версия Node.js

# Плагин Next.js для Netlify обычно устанавливается автоматически
# или его можно добавить через UI Netlify.
# Если вам нужны дополнительные функции, такие как Netlify Functions для API роутов,
# или Edge Functions, их конфигурация также может быть здесь.

# Пример для перенаправлений, если они нужны:
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
